apiVersion: v1
kind: ConfigMap
metadata:
  name: timeline-service-config
data:
  MONGODB_HOST: host.minikube.internal
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: mydatabase
  MONGODB_USER: admin
  MONGODB_PASS: admin
  USER_SERVICE_USERID_URL: http://192.168.49.2:80/v1/user/userid/
  API_PATH_ROOT: /v1/timeline
  KAFKA_CLIENT_ID: timeline
  KAFKA_HOST_PORT: 192.168.0.10:9092
  KAFKA_FANOUT_TOPIC: new-post
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  MONGODB_HOST: host.minikube.internal
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: mydatabase
  MONGODB_USER: admin
  MONGODB_PASS: admin
  API_PATH_DETAIL: /v1/user/detail
  API_PATH_SIGNUP: /v1/user/signup
  API_PATH_USERID: /v1/user/userid
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: follower-service-config
data:
  MONGODB_HOST: host.minikube.internal
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: mydatabase
  MONGODB_USER: admin
  MONGODB_PASS: admin
  API_PATH_ROOT: /v1/follower
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fanout-service-config
data:
  API_PATH_ROOT: /v1/fanout
  KAFKA_CLIENT_ID: fanout
  KAFKA_HOST_PORT: 192.168.0.10:9092
  KAFKA_FANOUT_TOPIC: new-post
  KAFKA_FANOUT_GROUP: fanout-group
  REDIS_HOST_PORT: redis://host.minikube.internal:6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timeline-service
  template:
    metadata:
      labels:
        app: timeline-service
    spec:
      containers:
        - name: timeline-service-container
          image: tareqjoy/timeline-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: timeline-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: timeline-service
spec:
  selector:
    app: timeline-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 5001
      nodePort: 30001
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: timeline-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: timeline-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-container
          image: tareqjoy/user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: user-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 5002
      nodePort: 30002
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: follower-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: follower-service
  template:
    metadata:
      labels:
        app: follower-service
    spec:
      containers:
        - name: follower-service-container
          image: tareqjoy/follower-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: follower-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: follower-service
spec:
  selector:
    app: follower-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 5003
      nodePort: 30003
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: follower-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: follower-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fanout-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fanout-service
  template:
    metadata:
      labels:
        app: fanout-service
    spec:
      containers:
        - name: fanout-service-container
          image: tareqjoy/fanout-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: fanout-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: fanout-service
spec:
  selector:
    app: fanout-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 5004
      nodePort: 30004
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fanout-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fanout-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
      - http:
          paths:
            - path: /v1/timeline/
              pathType: Prefix
              backend:
                service:
                  name: timeline-service
                  port:
                    number: 3001
            - path: /v1/user/
              pathType: Prefix
              backend:
                service:
                  name: user-service
                  port:
                    number: 3002
            - path: /v1/follower/
              pathType: Prefix
              backend:
                service:
                  name: follower-service
                  port:
                    number: 3003
            - path: /v1/fanout/
              pathType: Prefix
              backend:
                service:
                  name: fanout-service
                  port:
                    number: 3004
