/*
 * This source file was generated by the Gradle 'init' task
 */
package analytics;


import analytics.job.TopLikedPostJob;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("Starting Flink Analytics Jobs...");

        // Start the Flink job to process Kafka events
      //  TopLikedPostJob.runForString();
        TopLikedPostJob.run();
    }
}
