{
 "title": "Kafka",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "incoming-byte-rate",
   "type": "timeseries",
   "description": "The average number of incoming bytes received per second from all servers. Global request metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_incoming_byte_rate{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "incoming-byte-rate",
   "type": "timeseries",
   "description": "The average number of incoming bytes received per second from all servers. Global request metric.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_server_socket_server_metrics_outgoing_byte_rate{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Message & Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MessageIn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\", topic!~\"|__consumer_offsets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BytesInTotal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\", topic!~\"|__consumer_offsets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GlobalTopicCount",
   "type": "timeseries",
   "description": "The number of global partitions as observed by this Controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globaltopiccount{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BytesOutTotal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\", topic!~\"|__consumer_offsets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "ActiveControllerCount",
   "type": "timeseries",
   "description": "Indicates whether the broker is the controller broker. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ActiveBrokerCount",
   "type": "timeseries",
   "description": "The number of active brokers as observed by this controller. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activebrokercount{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GlobalPartitionCount",
   "type": "timeseries",
   "description": "The number of partitions across all topics in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_globalpartitioncount{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AtMinIsr",
   "type": "timeseries",
   "description": "The number of partitions whose in-sync replicas count is equal to the minIsr value.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_atminisr{job=\"kafka\", topic!~\"__consumer_offsets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ReplicasCount",
   "type": "gauge",
   "description": "A gauge metric that indicates the replica count per topic partition leader.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{job=\"kafka\", topic!~\"__consumer_offsets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InSyncReplicasCount",
   "type": "gauge",
   "description": "A gauge metric that indicates the in-sync replica count per topic partition leader.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_cluster_partition_insyncreplicascount{job=\"kafka\", topic!~\"__consumer_offsets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "linux-disk-read/write-bytes",
   "type": "timeseries",
   "description": "The total number of bytes read by the broker process, including reads from all disks. The total doesn’t include reads from page cache. Available only on Linux-based systems.\n\nThe total number of bytes written by the broker process, including writes from all disks. Available only on Linux-based systems.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_linux_disk_write_bytes{job=\"kafka\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_server_kafkaserver_linux_disk_read_bytes{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalTimeMs",
   "type": "timeseries",
   "description": "The total time in milliseconds to serve the specified request. - Produce: requests from producers to send data - FetchConsumer: requests from consumers to get data - FetchFollower: requests from follower brokers that are the followers of a partition to get new data",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_totaltimems{job=\"kafka\", quantile=\"0.99\", request=~\"Produce|FetchConsumer|FetchFollower\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "time-since-last-run-ms",
   "type": "gauge",
   "description": "A gauge metric that provides the time, in milliseconds, since the log cleaner last ran.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_log_logcleanermanager_time_since_last_run_ms{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Partition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "LogStartOffset",
   "type": "timeseries",
   "description": "The offset of the first message in a partition. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "kafka_log_log_logstartoffset{job=\"kafka\", topic!~\"__consumer_offsets\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LogEndOffset",
   "type": "timeseries",
   "description": "The offset of the last message in a partition.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "kafka_log_log_logendoffset{job=\"kafka\", topic!~\"__consumer_offsets\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}