{
 "title": "Zookeeper",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "ZooKeeperExpires",
   "type": "timeseries",
   "description": "The ZooKeeper session has expired. Note that when a session expires it could result in leader changes or possibly a new controller. You should monitor the number of these events across a Kafka cluster and if the overall number is high, you can do the following:\n\nCheck the health of your network\nCheck for garbage collection issues and tune it accordingly\nIf necessary, increase the session time out by setting the value of zookeeper.session.timeout.ms.\nFollowing are additional ZooKeeper metrics you can optionally observe on a Kafka broker.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeeperexpires_total{job=\"zookeeper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZooKeeperDisconnects",
   "type": "timeseries",
   "description": "A meter that provides the number of recent ZooKeeper client disconnects. Note that this metric does not tell you the number of disconnected clients or if ZooKeeper is down. The number does not change when a connection that was reported as disconnected is reestablished. In addition, this count returns to zero after about 90 minutes, even if the client never successfully reconnects to ZooKeeper. If you are checking system health, ZooKeeperExpiresPerSec is a better metric to help you determine this.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeeperdisconnects_total{job=\"zookeeper\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZooKeeperSyncConnects",
   "type": "timeseries",
   "description": "Reports the number of ZooKeeper client connections per second to execute operations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeepersyncconnects_total{job=\"zookeeper\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}