/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

val flinkVersion = "2.0.0"
val log4jVersion = "2.24.3"

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    compileOnly("org.apache.flink:flink-streaming-java:$flinkVersion")
    implementation("org.apache.flink:flink-clients:$flinkVersion")

    runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl:$log4jVersion")
    runtimeOnly("org.apache.logging.log4j:log4j-api:$log4jVersion")
    runtimeOnly("org.apache.logging.log4j:log4j-core:$log4jVersion")
}

// Configurations for shadow JAR
configurations {
    create("flinkShadowJar") {
        isCanBeResolved = true
        isCanBeConsumed = false
        // Always exclude these (also from transitive dependencies) since they are provided by Flink
        exclude(group = "org.apache.flink", module = "force-shading")
        exclude(group = "com.google.code.findbugs", module = "jsr305")
        exclude(group = "org.slf4j")
        exclude(group = "org.apache.logging.log4j")
    }
}

application.applicationDefaultJvmArgs = listOf("-Dlog4j.configurationFile=log4j2.properties")

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass.set("analytics.App")
}

sourceSets["main"].apply {
    compileClasspath += configurations["flinkShadowJar"]
    runtimeClasspath += configurations["flinkShadowJar"]
}

sourceSets["test"].apply {
    compileClasspath += configurations["flinkShadowJar"]
    runtimeClasspath += configurations["flinkShadowJar"]
}

// Fix Javadoc classpath issue
tasks.named<Javadoc>("javadoc") {
    classpath = sourceSets["main"].output + configurations["flinkShadowJar"]
}

tasks.jar {
    manifest {
        attributes(
            "Built-By" to System.getProperty("user.name"),
            "Build-Jdk" to System.getProperty("java.version")
        )
    }
}

// Configure shadow JAR
tasks.shadowJar {
    configurations = listOf(project.configurations["flinkShadowJar"])
}


tasks.named<JavaExec>("run") {
    classpath = sourceSets["main"].runtimeClasspath
}